### ISSUE TITLE
buckets created in EU (Ireland) don't work

### ISSUE THREAD

**Issue by davidsoergel** [davidsoergel/s3napback#4]
using version: 1.05

Steps to reproduce the problem:

Create EU (Ireland) bucket

try to backup to this bucket

Amazon sends redirection request which is not handled in s3napback.

It seams to be simillar problem as  http://code.google.com/p/lits3/issues/detail?id=18. More about redirection is written  here.
I tried to set configuration option Bucket to MYBUCKET.s3-external-3.amazonaws.com, which seams to be the destination server, but that does not work either.

The error I am getting:

```
Deleting...
AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Client.TemporaryRedirect
 faultSubcode:
 faultString: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint for future requests.
 faultActor:
 faultNode:
 faultDetail:
        {}Bucket:MYBUCKET
        {}Endpoint:MYBUCKET.s3-external-3.amazonaws.com

Please re-send this request to the specified temporary endpoint. Continue to usethe original request endpoint for future requests.
        at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
        at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
        at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:392)
        at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
        at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
        at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
        at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
        at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
        at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
        at org.apache.axis.client.Call.invoke(Call.java:2767)
        at org.apache.axis.client.Call.invoke(Call.java:2443)
        at org.apache.axis.client.Call.invoke(Call.java:2366)
        at org.apache.axis.client.Call.invoke(Call.java:1812)
        at com.amazonaws.s3.doc._2006_03_01.AmazonS3SoapBindingStub.listBucket(AmazonS3SoapBindingStub.java:1106)
        at net.sourceforge.js3tream.DeleteOperation.getBucketKeyList(DeleteOperation.java:148)
        at net.sourceforge.js3tream.DeleteOperation.start(DeleteOperation.java:93)
        at net.sourceforge.js3tream.Command.main(Command.java:334)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:616)
        at com.simontuffs.onejar.Boot.run(Boot.java:243)
        at com.simontuffs.onejar.Boot.main(Boot.java:89)
```

**Comment by davidsoergel** [comment]
It looks like this is a bug in the (now very old) Axis 1.4 library that js3tream uses. I suspect the easiest solution will be to upgrade js3tream to Axis2, but since that has a different API from the old one, it may turn out to be a substantial project. I can't get to it real soon I'm afraid. Anyone else want to take a stab at it?

**Comment by NightfallSD** [comment]
Hi mate. I have identical problem as above. Have you managed to find some workaround for him?
